# Generated by Django 5.0.7 on 2024-08-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_contact_number_organization_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_kyc_verified',
            field=models.BooleanField(default=False),
        ),
    ]
