# Generated by Django 5.0.7 on 2024-08-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_organization_is_kyc_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='established_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
