# Generated by Django 5.0.7 on 2024-08-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organization_established_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='is_kyc_verified',
            new_name='kyc_verified',
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
