# Generated by Django 5.0.7 on 2024-08-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_rename_is_kyc_verified_organization_kyc_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='contact_number',
            field=models.CharField(default='', max_length=13),
            preserve_default=False,
        ),
    ]
