# Generated by Django 5.0.7 on 2024-08-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_organization_city_organization_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='descripton',
            new_name='description',
        ),
    ]
