# Generated by Django 5.0.7 on 2024-08-07 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_rename_descripton_organization_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='logo',
        ),
    ]
