# Generated by Django 5.0.7 on 2024-09-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0010_alter_organization_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="industry",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="organization_logos/"
            ),
        ),
    ]
