# Generated by Django 5.0.7 on 2024-09-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0011_organization_industry_organization_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
