# Generated by Django 5.0.7 on 2024-08-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_userprofile_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[("ADMIN", "platform_user"), ("USER", "org_user")],
                default="USER",
                max_length=20,
            ),
        ),
    ]
