# Generated by Django 5.0.7 on 2024-09-10 09:55

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_userprofile_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp_secret",
            field=models.CharField(
                blank=True, default=pyotp.random_base32, max_length=32
            ),
        ),
    ]
