# Generated by Django 5.0.7 on 2024-09-15 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_user_otp_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="userprofile",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
