# Generated by Django 5.0.7 on 2024-09-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_orguserinvite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="contact_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
